import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  interface Student {
    name: string
    lastName: string
    rut: string
    class: string
    section: string
  }

  const initialState = {
    name: '',
    lastName: '',
    rut: '',
    class: '',
    section: '',
  }

  const [studentData, setStudentData] = useState<Student>(initialState)
  const [studentList, setStudentList] = useState<Student[] | null>(null)

  const addStudent = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    setStudentList(curr => curr && [...curr, studentData])
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setStudentData({ ...studentData, [e.target.name]: e.target.value })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Parvulapps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Parvulapps</h1>
        <p>Ingresa a los alumnos</p>

        <form onSubmit={addStudent}>
          <input
            type="text"
            placeholder="Nombre"
            name="name"
            value={studentData.name}
            onChange={handleChange}
          />
          <input
            type="text"
            placeholder="Apellido"
            name="lastName"
            value={studentData.lastName}
            onChange={handleChange}
          />
          <input
            type="text"
            placeholder="RUT"
            name="rut"
            value={studentData.rut}
            onChange={handleChange}
          />
          <input
            type="text"
            placeholder="curso"
            name="class"
            value={studentData.class}
            onChange={handleChange}
          />
          <input
            type="text"
            placeholder="seccion"
            name="section"
            value={studentData.section}
            onChange={handleChange}
          />
          <button type="submit">Enviar</button>
        </form>

        <div>
          <h2>Lista de estudiantes</h2>
          <ul>
            {studentList ? studentList.map((student, index) => {
              return <li key={index}>{student.name}</li>
            }) : ''}
          </ul>
        </div>
      </main>
    </div>
  )
}

export default Home
